=== moodyhunter/MoodyAPI/WgConfigGenerator/networks/node.schema.json
{
    "$schema": "http://json-schema.org/schema",
    "title": "MoodyAPI WireGuard Node Definition",
    "description": "A WireGuard Node in MoodyAPI",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "The name of the WireGuard Node",
            "default": "WireGuard Node"
        },
        "isServer": {
            "type": "boolean",
            "description": "Whether the WireGuard Node is a server",
            "default": false
        },
        "ipv4": {
            "type": "string",
            "description": "The IPv4 address of the WireGuard Node",
            "default": ""
        },
        "ipv6": {
            "type": "string",
            "description": "The IPv6 address of the WireGuard Node",
            "default": ""
        },
        "port": {
            "type": "integer",
            "description": "The port of the WireGuard Node",
            "default": 51820
        },
        "public_key": {
            "type": "string",
            "description": "The public key of the WireGuard Node",
            "default": ""
        },
        "private_key": {
            "type": "string",
            "description": "The private key of the WireGuard Node",
            "default": ""
        },
        "extra_allowed_ips": {
            "type": "array",
            "description": "The extra allowed IPs of the WireGuard Node, except its own IP",
            "items": {
                "type": "string"
            },
            "default": []
        },
        "public_endpoint": {
            "type": "string",
            "description": "The public IP endpoint of the WireGuard Node",
            "default": ""
        }
    }
}

=== moodyhunter/MoodyAPI/WgConfigGenerator/networks/demo_network/server.json
{
    "$schema": "../node.schema.json",
    "name": "WireGuard Server",
    "ipv4": "192.168.200.1",
    "ipv6": "fd00:1::1",
    "isServer": true,
    "private_key": "UCASsIuhyT5LLfhnx3nqRdbBJw1CszZ8xs9Vixkxv1c=",
    "public_endpoint": "server.wireguard.example.com:51820",
    "extra_allowed_ips": [
        "10.20.0.1/24"
    ]
}
